# PREVAIL
75da-2600-8800-13-3b00-d57b-fd2c-b617-85c5.ngrok-free.app: # dashboard.prevail-ed.com:
  logo: assets/logo-prevail.png
  
# LIGHTPATH
7714-2600-8800-13-3b00-d57b-fd2c-b617-85c5.ngrok-free.app: #dashboard.lightpathwealth.com:
  logo: assets/logo-lightpath.png
